name: Aditya's Test Workflow

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Assuming the root folder contains Code

      # Start server or setup environment if needed
      - name: Start Application Server (Optional)
        run: |
          # Uncomment and modify the following lines if a server is needed
          # nohup python path/to/your_server.py &

      - name: Run Tests
        run: |
          python -m pytest test/test_search.py --disable-warnings
